export default {
  residenceType: ['Own', 'Rent', 'Other'],
  planets: ['Mercury', 'Venus', 'Earth', 'Pandora', 'Tatooine', 'Hoth', 'Arrakis', 'Krypton'],
  countries: ['United States', 'Canada', 'United Kingdom', 'Australia'],
  employmentStatus: ['Full-time', 'Part-time', 'Self-employed', 'Unemployed', 'Student', 'Retired', 'Other'],
  educationLevel: ['High School Diploma', 'Other', "Bachelor's Degree"],
  clothingSize: ['XS', 'S', 'M', 'L', 'XL'],
  userDataFields: {
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email Address',
    confirmEmail: 'Confirm Email',
    phoneNumber: 'Phone Number',
    emergencyContactPhone: 'Emergency Contact Phone',
    emergencyContactName: 'Emergency Contact Name',
    userNationality: 'Nationality',
    userMaritalStatus: 'Marital Status',
    solarSystem: 'Solar system',
    userAddress: 'Street Address',
    userCountry: 'Country',
    userCurrentEmployer: 'Current Employer',
    userWorkPhone: 'Work Phone',
    userEmployerAddress: 'Employer Address',
    employerCity: 'Employer City',
    employerState: 'Employer State/Province',
    employerCountry: 'Employer Country',
    employerZipPostalCode: 'Employer ZIP/Postal Code',
    employerStartDate: 'Employment Start Date',
    yearsAtCurrentEmployer: 'Years at Current Employer',
    monthsAtCurrentEmployer: 'Months at Current Employer',
    annualIncome: 'Annual Income',
    incomeType: 'Income Type',
    userSolarSystem: 'Solar System',
  },
  races: ['Human', 'Molluscoid', 'Avian', 'Fungoid', 'Mammalien', 'Reptilian'],
  solarSystem: ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn'],
};
